### ISSUE TITLE
🗄 Build mobile drawer

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#101]
**Type**: client

**FOF**: 5

## Description
- We want to support a mobile drawer for the following mapview components
  - [Resource Sidebar (displays the resource cards)](https://github.com/ClearPathNYC/clearpath-web/blob/dev/src/pages/main/home/map/map-sidebar/index.tsx)
    - [Resource Card on Sidebar](https://github.com/ClearPathNYC/clearpath-web/blob/dev/src/pages/main/home/map/map-card/index.tsx) 
  - [Resource Popup (when a resource is selected)](https://github.com/ClearPathNYC/clearpath-web/blob/dev/src/components/resource-popup/index.tsx) 

## Screenshot
<img width="440" alt="image" src="https://user-images.githubusercontent.com/45826922/232365285-d62c1625-fdb4-401f-aa0a-faa69424faa6.png">
<img width="719" alt="image" src="https://user-images.githubusercontent.com/45826922/232365331-6554a4fe-7c9a-4672-bd14-99cf000b626d.png">

## Todo

- [ ] Support drawer functionality for open/close views on drag
- [ ] Drawer-ify the resource map and resource popup content

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

**Comment by ajain1921** [comment]
:O
