### ISSUE TITLE
⚒️ Fix edit profile page for users

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#132]
**Type**: client

**FOF**: 2

## Description
- Currently the edit profile page doesn't allow users to save their changes
  - Route: http://localhost:3000/profile
- We've done something similar with the nonprofit profile page
  - Route: http://localhost:3000/organization/profile
  - This page works, so feel free to use it for reference

## Screenshot
<img width="1552" alt="image" src="https://github.com/ClearPathNYC/clearpath-web/assets/45826922/64753117-d3ee-4fa8-9eb5-f7df9a26c6b7">

## Where's the code?
- User Profile
  - https://github.com/ClearPathNYC/clearpath-web/blob/dev/src/pages/main/user-profile/index.tsx
  - This is the file you'll be working in
- Nonprofit Profile
  - https://github.com/ClearPathNYC/clearpath-web/blob/dev/src/pages/organization-dashboard/organization-profile/index.tsx
  - This is the working code that you can reference

## What do you need to do?
- Currently, the code that connects to the backend to update the user profile is commented out
  - Lines 68-97 in `user-profile/index.tsx`
  - Your job is to debug this code so that it successfully updates the user profile 
``` typescript
onSubmit={async (formBody, helpers) => {
  console.log("here", formBody);
  try {
    // const requestBody = {
    //   id: userId,
    //   race: formBody.race || "",
    //   sexuality: formBody.sexuality || "",
    //   gender: formBody.level || "",
    //   dob: formBody.level || "",
    //   firstName: formBody.level || "",
    //   lastName: formBody.level || "",
    //   priorAcademics: {
    //     level: formBody.level || "",
    //     school: formBody.school || "",
    //     department: formBody.department || "",
    //     specialization: formBody.specialization || "",
    //     yearOfGrad: formBody.yearOfGrad || "",
    //   },
    // };
    // const response = await updateUserDetails(requestBody).unwrap();
    // console.log("response", response);

    helpers.setSubmitting(false);
    // dispatch(updateDetails(response.user));
    history.push(ROUTES.Home);
  } catch (error) {
    // console.log(error);
    // dispatch(throwError({ type: "AUTH/ERROR/SIGNIN", error }));
  }
}}
```

## Things to know
- The blue "Save changes" button won't work until all the required data is filled out
  - In https://github.com/ClearPathNYC/clearpath-web/blob/dev/src/pages/main/user-profile/config.ts you can see the `userProfileValidationSchema` that they use to validate the user inputs
- Here is the backend endpoint that your form is connecting to when it calls `await updateUserDetails(requestBody)` on line 87
<img width="503" alt="image" src="https://github.com/ClearPathNYC/clearpath-web/assets/45826922/0aa59d6f-051e-4887-b65c-f19f37237194">

## Todo
- [ ] Debug the code so that it successfully updates the user profile
  - You know it's working when you revisit your user profile and the page is pre-populated with your info
- [ ] Make the Cancel button do something
  - Currently it does nothing
  - Make it redirect to map resource dashboard?  

## Links
- [Formik Docs](https://formik.org/docs/overview)
- [Yup Validation](https://github.com/jquense/yup)

## Learnings
- Fixing code you didn't write

**Comment by EidanGar** [comment]
@ayanmallik Hello, can I help with this issue?
