### ISSUE TITLE
📺 Display remote resources on sidebar

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#133]
**Type**: client

**FOF**: 2

## Description
- Currently, we only display in-person resources on the sidebar that appear on the map view
- We want to append remote resources to the list on the resource sidebar

## Screenshot
<img width="812" alt="image" src="https://github.com/ClearPathNYC/clearpath-web/assets/45826922/c486c931-028d-42fb-995d-735cea6a4666">

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

**Comment by ajain1921** [comment]
Closed by commit 5085e96a974c63019eb274927109ad88e8c2ff03
