### ISSUE TITLE
🔎 Create resource search bar

### ISSUE THREAD

**Issue by ayanmallik** [ClearPathNYC/clearpath-web#59]
**Type**: client

**FOF**: 1

## Description
- We want to enable users to search for resources by
  - name
  - category (housing support, academic development, ...)
  - tags (college, online, ...)
- Refer to #7 and #10, or just talk to Aditya 😉 

## Screenshot
- Build out the search bar using ClearPath's `<Input />` component

<img width="726" alt="image" src="https://user-images.githubusercontent.com/45826922/227853704-1784bc40-e615-4813-87d0-e538835700ae.png">

## Todo

- [ ] Create the resource search bar
- [ ] Position the search on the user dashboard (`/dashboard`)

## Links

- [Figma](https://www.figma.com/file/qELi7Tz3K4XxXQmCVrrpRE/Clear-Path-x-H4I?node-id=1%3A2&t=wnmmIblE2fpTrpNM-0)
- [Styled Components Tips](https://javascript.plainenglish.io/react-7-tricks-to-work-with-styled-components-20eb155934b1)

**Comment by EidanGar** [comment]
Hello, is this repository open for outside contributions? I'm interested in completing this task.
